apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec: 
      containers:
      - name: zookeeper-pod
        image: zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "zookeeper-svc"
  namespace: "default"
  labels:
    app: "zookeeper"
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    port: 2181
    targetPort: 2181
    